// components/StackblitzLauncher.js
import React from "react";
import sdk from "@stackblitz/sdk";

const StackblitzLauncher = ({ html, css, js, title = "AI Website" }) => {
  const openStackBlitz = () => {
    sdk.openProject(
      {
        title,
        description: "Website generated by AI assistant",
        template: "javascript", // or "node" if needed
        files: {
          "index.html": html || "<h1>Hello world</h1>",
          "style.css": css || "body { font-family: sans-serif; }",
          "index.js": js || "console.log('Running!')",
        },
      },
      {
        openFile: "index.html",
      }
    );
  };

  return (
    <button
      onClick={openStackBlitz}
      className="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700 transition"
    >
      Open in StackBlitz
    </button>
  );
};

export default StackblitzLauncher;
